<?php
// module/Comments/view/comments/comments/index.phtml:

$title = 'Comments module';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('comments', ['action' => 'add']) ?>">Write comment</a>
</p>


<div class="comments_wrap">
    <?php echo $this->Comments()->render( $comments ); ?>
</div>


<?= $this->paginationControl(
    // The paginator object:
    $paginator,
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'comments']
) ?>